"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.THDToken__factory = exports.PaymentChannel__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var PaymentChannel__factory_1 = require("./PaymentChannel__factory");
Object.defineProperty(exports, "PaymentChannel__factory", { enumerable: true, get: function () { return PaymentChannel__factory_1.PaymentChannel__factory; } });
var THDToken__factory_1 = require("./THDToken__factory");
Object.defineProperty(exports, "THDToken__factory", { enumerable: true, get: function () { return THDToken__factory_1.THDToken__factory; } });
//# sourceMappingURL=index.js.map